# Generated by Django 5.2.7 on 2025-10-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Session_counter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address_url", models.CharField(max_length=500, null=True)),
                ("count", models.IntegerField(default=0)),
            ],
        ),
    ]
