# Generated by Django 5.2.7 on 2025-11-04 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="company",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RemoveField(
            model_name="department",
            name="personnel",
        ),
        migrations.AddField(
            model_name="department",
            name="personnel",
            field=models.ManyToManyField(
                related_name="assigned_departments", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
